apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system

helmCharts:
  - name: karpenter-crd
    repo: oci://public.ecr.aws/karpenter
    version: 1.12.0
    releaseName: karpenter-crd
    namespace: kube-system
  - name: karpenter
    repo: oci://public.ecr.aws/karpenter
    version: 1.12.0
    releaseName: karpenter
    namespace: kube-system
    valuesFile: override-values-v1.12.0.yaml
