apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: alloy

resources: []

helmCharts:
  - name: alloy
    releaseName: alloy-edge
    repo: https://grafana.github.io/helm-charts
    version: 0.11.0
    valuesFile: edge-values.yaml
    includeCRDs: false

