apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: infrastructure-critical
value: 800000
globalDefault: false
description: "Used for core observability and networking components."
