nginxGateway:
  # The dynamic configuration for the control plane that is contained in the NginxGateway resource.
  config:
    logging:
      # @schema
      # enum:
      #   - info
      #   - debug
      #   - error
      # @schema
      # -- Log level.
      level: info

  # -- The number of replicas of the NGINX Gateway Fabric Deployment. This value is ignored if autoscaling.enable is true.
  replicas: 3

  # -- The termination grace period of the NGINX Gateway Fabric control plane pod.
  terminationGracePeriodSeconds: 30

  # -- Autoscaling configuration for the NGINX Gateway Fabric control plane.
  autoscaling:
    # -- Enable or disable Horizontal Pod Autoscaler for the control plane.
    enable: true
    # -- Set of custom annotations for the HPA object.
    annotations: {}
    # -- Minimum number of replicas for the NGINX data plane HPA.
    minReplicas: 1
    # -- Maximum number of replicas for the NGINX data plane HPA.
    maxReplicas: 3
    # -- Target CPU utilization percentage for the NGINX data plane HPA. Requires `nginx.container.resources` to be set.
    targetCPUUtilizationPercentage: 50
    # -- Target memory utilization percentage for the NGINX data plane HPA. Requires `nginx.container.resources` to be set. |
    targetMemoryUtilizationPercentage: 50
    # -- The full HPA `spec.behavior` object, passed as-is to the HPA resource. Accepts any valid Kubernetes HPA behavior spec. See the [Kubernetes docs](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/#configurable-scaling-behavior) for all available fields.
    behavior: # {}
      scaleDown:
        stabilizationWindowSeconds: 300
        policies:
        - type: Pods
          value: 1
          periodSeconds: 180
      scaleUp:
        stabilizationWindowSeconds: 30
        policies:
        - type: Pods
          value: 2
          periodSeconds: 30
    # -- Custom or additional autoscaling metrics. https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/#scaling-on-custom-metrics
    metrics: []
    # - type: Pods
    #   pods:
    #     metric:
    #       name: container_memory_usage_bytes
    #     target:
    #       type: AverageValue
    #       averageValue: "400Mi"

  metrics:
    # -- Enable exposing metrics in the Prometheus format.
    enable: true

    # @schema
    # type: integer
    # minimum: 1
    # maximum: 65535
    # @schema
    # -- Set the port where the Prometheus metrics are exposed.
    port: 9113

    # -- Enable serving metrics via https. By default metrics are served via http.
    # Please note that this endpoint will be secured with a self-signed certificate.
    secure: false


# -- The nginx section contains the configuration for all NGINX data plane deployments
# installed by the NGINX Gateway Fabric control plane.
nginx:
  # @schema
  # enum:
  #   - deployment
  #   - daemonSet
  # @schema
  # -- The kind of NGINX deployment.
  kind: deployment

  # -- The number of replicas of the NGINX Deployment. This value is ignored if autoscaling.enable is true.
  replicas: 3

  # -- Custom patches to apply to the NGINX Deployment/DaemonSet.
  patches: # []
  # -- Example:
  # - type: StrategicMerge
  #   value:
  #     metadata:
  #       labels:
  #         team: "nginx-gateway-fabric"

  # -- Autoscaling configuration for the NGINX data plane.
  autoscaling:
    # -- Enable or disable Horizontal Pod Autoscaler for the NGINX data plane.
    enable: true
    # -- Set of custom annotations for the HPA object.
    annotations: {}
    # -- Minimum number of replicas for the NGINX data plane HPA.
    minReplicas: 1
    # -- Maximum number of replicas for the NGINX data plane HPA.
    maxReplicas: 3
    # -- Target CPU utilization percentage for the NGINX data plane HPA. Requires `nginx.container.resources` to be set.
    targetCPUUtilizationPercentage: 50
    # -- Target memory utilization percentage for the NGINX data plane HPA. Requires `nginx.container.resources` to be set. |
    targetMemoryUtilizationPercentage: 50
    # -- The full HPA `spec.behavior` object, passed as-is to the HPA resource. Accepts any valid Kubernetes HPA behavior spec. See the [Kubernetes docs](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/#configurable-scaling-behavior) for all available fields.
    behavior: # {}
      scaleDown:
        stabilizationWindowSeconds: 300
        policies:
        - type: Pods
          value: 1
          periodSeconds: 180
      scaleUp:
        stabilizationWindowSeconds: 300
        policies:
        - type: Pods
          value: 2
          periodSeconds: 60
    # -- Custom or additional autoscaling metrics. https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/#scaling-on-custom-metrics
    metrics: []
    # - type: Pods
    #   pods:
    #     metric:
    #       name: nginx_gateway_fabric_nginx_process_requests_total
    #     target:
    #       type: AverageValue
    #       averageValue: "400Mi"

# -- The pod configuration for the NGINX data plane pod. This is applied globally to all Gateways managed by this
# instance of NGINX Gateway Fabric.
pod: # {}
  # -- The termination grace period of the NGINX data plane pod.
  # terminationGracePeriodSeconds: 30
  terminationGracePeriodSeconds: 30

  # -- Tolerations for the NGINX data plane pod.
  # tolerations: []

  # -- The nodeSelector of the NGINX data plane pod.
  # nodeSelector: {}

  # -- The topology spread constraints for the NGINX data plane pod.
  # topologySpreadConstraints: []
  topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: topology.kubernetes.io/zone
      whenUnsatisfiable: DoNotSchedule
      labelSelector:
        matchLabels:
          app.kubernetes.io/instance: ngf

    - maxSkew: 1
      topologyKey: kubernetes.io/hostname
      whenUnsatisfiable: ScheduleAnyway
      labelSelector:
        matchLabels:
          app.kubernetes.io/instance: ngf

  # -- The volumes for the NGINX data plane pod. Use in conjunction with
  # nginx.container.volumeMounts mount additional volumes to the container.
  # volumes: []


# -- The container configuration for the NGINX container. This is applied globally to all Gateways managed by this
# instance of NGINX Gateway Fabric.
container:
  # @schema
  # type: array
  # items:
  #   type: object
  #   properties:
  #     port:
  #       type: integer
  #       required: true
  #       minimum: 1
  #       maximum: 65535
  #     containerPort:
  #       type: integer
  #       required: true
  #       minimum: 1
  #       maximum: 65535
  # @schema
  # -- A list of HostPorts to expose on the host.
  # This configuration allows containers to bind to a specific port on the host node,
  # enabling external network traffic to reach the container directly through the host's IP address and port.
  # Use this option when you need to expose container ports on the host for direct access,
  # such as for debugging, legacy integrations, or when NodePort/LoadBalancer services are not suitable.
  # Note: Using hostPort may have security and scheduling implications, as it ties pods to specific nodes and ports.
  hostPorts: []
  # - port: 80
  #   containerPort: 80

  # -- The resource requirements of the NGINX container. You should set this value if you want to use dataplane Autoscaling(HPA).
  resources: # {}
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 300m
      memory: 256Mi

  # -- The lifecycle of the NGINX container.
  lifecycle: {}

  # -- volumeMounts are the additional volume mounts for the NGINX container.
  volumeMounts: []

  ## -- Defines the settings for the data plane readiness probe. This probe returns Ready when the NGINX data plane is ready to serve traffic.
  readinessProbe: {}
    # @schema
    # type: integer
    # minimum: 1
    # maximum: 65535
    # @schema
    # -- Port in which the readiness endpoint is exposed.
    # port: 8081

    # -- The number of seconds after the Pod has started before the readiness probes are initiated.
    # initialDelaySeconds: 3


# -- The service configuration for the NGINX data plane. This is applied globally to all Gateways managed by this
# instance of NGINX Gateway Fabric.
service:
  # @schema
  # enum:
  #   - ClusterIP
  #   - NodePort
  #   - LoadBalancer
  # @schema
  # -- The type of service to create for the NGINX data plane.
  type: LoadBalancer

  # @schema
  # enum:
  #   - Cluster
  #   - Local
  # @schema
  # -- The externalTrafficPolicy of the service. The value Local preserves the client source IP.
  externalTrafficPolicy: Local

  # -- The static IP address for the load balancer. Requires nginx.service.type set to LoadBalancer.
  loadBalancerIP: ""

  # -- LoadBalancerClass is the class of the load balancer implementation this Service belongs to.
  # Requires nginx.service.type set to LoadBalancer.
  loadBalancerClass: ""

  # -- The IP ranges (CIDR) that are allowed to access the load balancer. Requires nginx.service.type set to LoadBalancer.
  loadBalancerSourceRanges: []

  # @schema
  # type: array
  # items:
  #   type: object
  #   properties:
  #     port:
  #       type: integer
  #       required: true
  #       minimum: 1
  #       maximum: 65535
  #     listenerPort:
  #       type: integer
  #       required: true
  #       minimum: 1
  #       maximum: 65535
  # @schema
  # -- A list of NodePorts to expose on the NGINX data plane service. Each NodePort MUST map to a Gateway listener port,
  # otherwise it will be ignored. The default NodePort range enforced by Kubernetes is 30000-32767.
  nodePorts: []
  # - port: 30025
  #   listenerPort: 80

  # -- Custom patches to apply to the NGINX Service.
  patches: # []
  # -- Example:
  #   - type: JSONPatch
  #     value:
  #       - op: replace
  #         path: /spec/sessionAffinity
  #         value: "ClientIP"
    - type: StrategicMerge
      value:
        metadata:
          annotations:
            service.beta.kubernetes.io/aws-load-balancer-type: "external"
            service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
            service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"

# -- Enable debugging for NGINX. Uses the nginx-debug binary. The NGINX error log level should be set to debug in the NginxProxy resource.
debug: false
