apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-load-balancer-controller
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    argocd.argoproj.io/sync-options: Prune=confirm

spec:
  project: default

  source:
    repoURL: https://github.com/Yerdaulet-zh/aws-eks.git
    targetRevision: HEAD
    path: manifests/base/aws-load-balancer-controller

  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system

  ignoreDifferences:

    # Runtime deployment mutations
    - group: apps
      kind: Deployment
      name: aws-load-balancer-controller
      namespace: kube-system
      jsonPointers:
        - /spec/replicas
        - /status

    # Webhook CA bundle injection
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      jqPathExpressions:
        - '.webhooks[]?.clientConfig.caBundle'

    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      jqPathExpressions:
        - '.webhooks[]?.clientConfig.caBundle'

    # Service status mutations
    - group: ""
      kind: Service
      jsonPointers:
        - /status

  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
      allowEmpty: true

    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
      - ApplyOutOfSyncOnly=true
      - PruneLast=true
      - RespectIgnoreDifferences=true
