apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-gateway-dev
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://github.com/Yerdaulet-zh/aws-eks.git
    targetRevision: HEAD
    path: manifests/base/gateway/nginx
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx-gateway
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  ignoreDifferences:
    # Ignore metadata that the API server or controllers add automatically
    - group: ""
      kind: ConfigMap
      jsonPointers:
        - /metadata/annotations/control-plane.alpha.kubernetes.io~1leader
    # Ignore fields in Gateway resources that are managed by the controller
    - group: gateway.networking.k8s.io
      kind: Gateway
      jsonPointers:
        - /metadata/annotations
    # Often the NGINX Gateway adds dynamic certificates or secrets
    - group: ""
      kind: Secret
      jsonPointers:
        - /data
    # ignore the "ghosting" status fields
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      jsonPointers:
        - /status # Ignore the status updates from the NGINX controller
    - group: gateway.networking.k8s.io
      kind: Gateway
      jsonPointers:
        - /status
        - /metadata/annotations
