apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-cluster-wide-crds
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  project: default
  source:
    repoURL: https://github.com/Yerdaulet-zh/aws-eks.git
    targetRevision: HEAD
    path: manifests/base/gateway/nginx/bootstrap
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
