apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - gateway.nginx.org_authenticationfilters.yaml
  - gateway.nginx.org_ratelimitpolicies.yaml
  - gateway.nginx.org_clientsettingspolicies.yaml
  - gateway.nginx.org_snippetsfilters.yaml
  - gateway.nginx.org_nginxgateways.yaml
  - gateway.nginx.org_snippetspolicies.yaml
  - gateway.nginx.org_nginxproxies.yaml
  - gateway.nginx.org_upstreamsettingspolicies.yaml
  - gateway.nginx.org_observabilitypolicies.yaml
  - gateway.nginx.org_proxysettingspolicies.yaml
