apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: python
  namespace: nginx-gateway
spec:
  parentRefs:
  - name: my-ipv4-gateway
    namespace: nginx-gateway
    group: gateway.networking.k8s.io
    kind: Gateway
    sectionName: https
  hostnames:
  - "fastapi.imon.work"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: fastapi-service
      namespace: backend-dev
      group: ""
      kind: Service
      port: 80
      weight: 1
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: argocd
  namespace: nginx-gateway
spec:
  parentRefs:
  - name: my-ipv4-gateway
    namespace: nginx-gateway
    group: gateway.networking.k8s.io
    kind: Gateway
    sectionName: https
  hostnames:
  - "argocd.imon.work"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: argocd-server
      namespace: argocd
      group: ""
      kind: Service
      port: 443
      weight: 1
