apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: fastapi-monitor
  namespace: fastapi
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: fastapi
  namespaceSelector:
    matchNames:
      - fastapi
  endpoints:
  - port: http-metrics
    path: /metrics
    interval: 15s
