apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
  namespace: fastapi
  labels:
    app: fastapi  # This must match the ServiceMonitor selector
spec:
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http-metrics
  selector:
    app: fastapi
