apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nginx-gateway-dev

resources:
  - ../../../../base/nginx-gateway/

labels:
  - pairs:
      env: development
    includeTemplates: true
    includeSelectors: false

patches:
  - target:
      kind: Namespace
      name: nginx-gateway
    patch: |-
      - op: replace
        path: /metadata/name
        value: nginx-gateway-dev

helmCharts:
  - name: nginx-gateway-fabric
    repo: oci://ghcr.io/nginx/charts/
    version: 2.5.1
    releaseName: ngf
    valuesFile: values.yaml
