apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: imon-work-wildcard
  namespace: nginx-gateway
spec:
  secretName: imon-work-wildcard-tls
  issuerRef:
    name: letsencrypt-dns
    kind: ClusterIssuer
  commonName: "*.imon.work"
  dnsNames:
    - "*.imon.work"
    - "imon.work"
