apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-dns
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: yerdaulet.art@gmail.com
    privateKeySecretRef:
      name: letsencrypt-dns-secret-key
    solvers:
    - dns01:
        route53:
          region: eu-central-1
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: imon-work-wildcard
  namespace: nginx-gateway
spec:
  secretName: imon-work-wildcard-tls
  issuerRef:
    name: letsencrypt-dns
    kind: ClusterIssuer
  dnsNames:
  - "imon.work"
  - "*.imon.work"
