apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system

resources:
  - github.com/aws/eks-charts/stable/aws-load-balancer-controller/crds?ref=master

helmCharts:
  - name: aws-load-balancer-controller
    releaseName: aws-load-balancer-controller
    repo: https://aws.github.io/eks-charts
    version: 3.2.2
    valuesInline:
      clusterName: "eks-academy-dev"
      vpcId: "vpc-07cd1651bb52b7d36"
      region: "eu-central-1"
      priorityClassName: system-cluster-critical

      installCRDs: true

      enableCertManager: true
      serviceAccount:
        create: true
        name: aws-load-balancer-controller
