global:
  domain: "argocd.imon.academy"

  logging:
    # -- Set the global logging format. Either: `text` or `json`
    format: json
    # -- Set the global logging level. One of: `debug`, `info`, `warn` or `error`
    level: info

  # -- Tolerations for pod assignment
  tolerations:
    - key: "ClusterManagement"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"

# Enable Insecure ArgoCD API Server
configs:
  params:
    server.insecure: true
  cm:
    kustomize.buildOptions: "--enable-helm"

# HA mode with autoscaling
redis-ha:
  enabled: true
  # --- did not respect the global setting
  tolerations:
    - key: "ClusterManagement"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"

controller:
  replicas: 1

server:
  autoscaling:
    enabled: true
    minReplicas: 2

repoServer:
  autoscaling:
    enabled: true
    minReplicas: 2

applicationSet:
  replicas: 2
